  - package-ecosystem: "npm"  # 'npm' works for both npm and Yarn projects
    directory: "/"  # Path to where your `package.json` and `yarn.lock` are located
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
